[google_oauth]
client_id = "874816672810-5erhmeo2f0qg4en24cn5bgsvib986kvb.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://softwareandlifeassessment-ec3ls5wdtdqbdcgc2y2quv.streamlit.app/"
